"""
Streamlit Dashboard for Evidently Reports
"""

import streamlit as st
import os
from pathlib import Path

# Page config
st.set_page_config(
    page_title="Mobile Sentiment Analysis - Monitoring",
    page_icon="📱",
    layout="wide"
)

# Title
st.title("📱 Mobile Reviews Sentiment Analysis - Model Monitoring")
st.markdown("---")

# Description
st.markdown("""
This dashboard displays data quality and model performance reports generated by Evidently AI.
Reports are automatically created during model training.
""")

# Report path
report_path = "/app/reports/report.html"

# Check if report exists
if os.path.exists(report_path):
    st.success("✅ Latest Evidently Report Available")
    
    # Read report
    with open(report_path, 'r', encoding='utf-8') as f:
        report_html = f.read()
    
    # Display report
    st.components.v1.html(report_html, height=1200, scrolling=True)
    
else:
    st.warning("⚠️ No report found. Train a model first to generate the report.")
    st.markdown("""
    ### To generate a report:
    
    1. Use the `/model/train` API endpoint with your training data
    2. Or trigger the Airflow DAG `train_sentiment_model_dag`
    3. The report will be automatically generated and displayed here
    
    **API Example:**
    ```bash
    curl -X POST http://localhost:8080/model/train \\
      -F "file=@Mobile_Reviews_Sentiment.csv"
    ```
    """)

# Sidebar
st.sidebar.title("ℹ️ About")
st.sidebar.markdown("""
### Mobile Sentiment MLSecOps

This pipeline predicts sentiment (Positive, Negative, Neutral) 
for mobile phone reviews.

**Features:**
- XGBoost classifier
- MLflow experiment tracking
- Airflow orchestration
- Evidently AI monitoring
- Docker containerization

**Metrics Tracked:**
- Accuracy (train/test)
- Precision, Recall, F1 per class
- Confusion matrix
- Data quality metrics
""")

st.sidebar.markdown("---")
st.sidebar.markdown("**Services:**")
st.sidebar.markdown("- API: http://localhost:8080")
st.sidebar.markdown("- MLflow: http://localhost:5102")
st.sidebar.markdown("- Airflow: http://localhost:8090")
st.sidebar.markdown("- Dashboard: http://localhost:8501")
